# Exception Handling
# normal termination
try:
    print('Micky-1')
    print('Micky-2')
    print('Micky'+10)    
except TypeError as z:
    print('Exception raised due to : ',z)    
print()
print('Rest of the code...')

