# Exception Handling
# normal termination
try:
    print('Micky-1')
    print('Micky-2')      
except:
    print('Exception raised due to : ')    

print()
print('Rest of the code...')

